version: "3"

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: ssh-news-app
    tty: true
    volumes:
      - ./logs:/app/logs
      - ./.ssh:/app/.ssh
    environment:
#        - LOG_FILE_PATH=/app/logs  todo support log file path
        - LOG_FILE=1
        - PORT=32000
        - TZ=Asia/Shanghai
    ports:
      - "32000:32000"
    restart: always